### ISSUE TITLE
UnhandledSchemeError using the set up

### ISSUE THREAD

**Issue by LucaSchirmer** [designsystemsinternational/mechanic#181]
<h2>Unhandled Scheme</h2>
I used the npm init mechanic@latest command and set it up. Then I run it and i get this error:

<br><br>
<code>ERROR in C:UsersLucaSOneDriveDesktopmechanicDesignprogram
ode_modules@mechanic-designcoreappINPUTS
Module build failed: UnhandledSchemeError: Reading from "C:UsersLucaSOneDriveDesktopmechanicDesignprogram
ode_modules@mechanic-designcoreappINPUTS" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "c:" URIs.
    at C:\Users\LucaS\OneDrive\Desktop\mechanicDesign\program\node_modules\webpack\lib\NormalModule.js:838:25
    at Hook.eval [as callAsync] (eval at create (C:\Users\LucaS\OneDrive\Desktop\mechanicDesign\program\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\LucaS\OneDrive\Desktop\mechanicDesign\program\node_modules\tapable\lib\Hook.js:18:14)
    at Object.processResource (C:\Users\LucaS\OneDrive\Desktop\mechanicDesign\program\node_modules\webpack\lib\NormalModule.js:835:8)
    at processResource (C:\Users\LucaS\OneDrive\Desktop\mechanicDesign\program\node_modules\loader-runner\lib\LoaderRunner.js:220:11)
    at iteratePitchingLoaders (C:\Users\LucaS\OneDrive\Desktop\mechanicDesign\program\node_modules\loader-runner\lib\LoaderRunner.js:171:10)
    at runLoaders (C:\Users\LucaS\OneDrive\Desktop\mechanicDesign\program\node_modules\loader-runner\lib\LoaderRunner.js:398:2)
    at NormalModule._doBuild (C:\Users\LucaS\OneDrive\Desktop\mechanicDesign\program\node_modules\webpack\lib\NormalModule.js:825:3)
    at NormalModule.build (C:\Users\LucaS\OneDrive\Desktop\mechanicDesign\program\node_modules\webpack\lib\NormalModule.js:969:15)
    at C:\Users\LucaS\OneDrive\Desktop\mechanicDesign\program\node_modules\webpack\lib\Compilation.js:1377:12
    at NormalModule.needBuild (C:\Users\LucaS\OneDrive\Desktop\mechanicDesign\program\node_modules\webpack\lib\NormalModule.js:1257:32)
    at Compilation._buildModule (C:\Users\LucaS\OneDrive\Desktop\mechanicDesign\program\node_modules\webpack\lib\Compilation.js:1358:10)
    at C:\Users\LucaS\OneDrive\Desktop\mechanicDesign\program\node_modules\webpack\lib\util\AsyncQueue.js:305:10
    at Hook.eval [as callAsync] (eval at create (C:\Users\LucaS\OneDrive\Desktop\mechanicDesign\program\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncQueue._startProcessing (C:\Users\LucaS\OneDrive\Desktop\mechanicDesign\program\node_modules\webpack\lib\util\AsyncQueue.js:295:26)
    at AsyncQueue._ensureProcessing (C:\Users\LucaS\OneDrive\Desktop\mechanicDesign\program\node_modules\webpack\lib\util\AsyncQueue.js:282:12)
    at process.processImmediate (node:internal/timers:476:21)
 @ ../../../../AppData/Local/Temp/tmp-func-mechanic---2948-i1QcJbD1Ra3N/fnc.js 4:0-133 7:6-16 7:34-45

webpack 5.88.2 compiled with 1 error in 5816 ms
</code>
The error within the webpackConfigGenerator.cjs - atleast that's what i guess - since it is the only time within the source code that webpack is used. This is the URL request the makes the error happen: C:UsersLucaSOneDriveDesktopmechanicDesignprogram
ode_modules@mechanic-designcoreappINPUTS

the actual URL should be C:/Users/LucaS/OneDrive/Desktop/mechanicDesign/program/node_modules/@mechanic-design/core/app/INPUTS

but the URL that is webpack is using is something like: 
C:\Users\LucaS\OneDrive\Desktop\mechanicDesign\program\node_modules\@mechanic-design\core\app\INPUTS

It gets the line break because of the \n.
program\node_modules\@mechanic-design\core\app\INPUTS

It gets the line break because of the \n.

mechanicDesign\program\node_modules\webpack\lib\util\URLAbsoluteSpecifier.js

I actually even written a filter in that file to filter out the URL that makes trouble and when I change the output of the getScheme() function I run into an other error that tell me that and I can't fix it cause it is writing into a js-file in the temp folder with the name of the design function. 

<h2><b>To Reproduce</b></h2>
I actually tried a lot other different things and always ran into the error. I even tried it out from my laptop but nothing changes. I updated npm etc.

1. In the VSCode termil I enter the command npm init mechanic@latest
2. Then I give my project a name (in this case program) 
3. I have chosen a lot of different projects - I got it everytime => I tried to create all the examples; and I tried to create a template but every single time when running the programm it gives me the error
4. I also I agree to do a design function 
5. Then I choose npm to install it and also let it automatically install all the node packages which it needs to make it running
6. Afterwards I open the newly created folder program (cd program) 
7. Finally I run the command npm run dev
8. Et voila the error occurs 

- OS: windows 10

**Comment by fdoflorenzano** [comment]
@LucaSchirmer the fix is in the codebase, but not published yet. I'll let you know when it is

**Comment by fdoflorenzano** [comment]
2.0.0-beta.11 is published and includes the fix! if you ran `npm init mechanic@latest` again, it should work now!

**Comment by LucaSchirmer** [comment]
Now it works! 

Great Job there - thank you for fast responsive!
